### ISSUE TITLE
Supporting query parameters

### ISSUE THREAD

**Issue by boedy** [renedx/node-moneybird#2]
Many GET endpoints support some sort of filter option which are passed through query parameters. 

Any plans to implement this?

**Comment by rdzar** [comment]
Didn't run into this yet, will have a look :) Shouldn't be a problem!

**Comment by rickvdl** [comment]
@boedy @renedx Hi all, I've added the option in #3.

**Comment by ben-kn-app** [comment]
Can the elegant solution of @rickvdl be merged?

**Comment by dvh** [comment]
I need this feature as well, when is the next release planned?

**Comment by DeviaVir** [comment]
@dvh FYI in case you are not aware you can install specific commit refs:
```
npm install git://github.com/renedx/node-moneybird/#f6faa8aea273477b68cd9470f957ce09aaefc2fa --save
```

**Comment by dvh** [comment]
@DeviaVir never done that before, but if I do that it only resolves `LICENSE`, `package.json` and `README.md` in `node_modules/moneybird`. Any suggestions? :)
